# TCL File Generated by Component Editor 17.1
# Mon May 02 03:56:08 CEST 2022
# DO NOT MODIFY


# 
# tanh_instruct "tanh_instruct" v1.0
#  2022.05.02.03:56:08
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module tanh_instruct
# 
set_module_property DESCRIPTION ""
set_module_property NAME tanh_instruct
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP myIPs
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tanh_instruct
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL d_tanh_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file math_utility.vhd VHDL PATH math_utility.vhd IS_CONFIGURATION_PACKAGE
add_fileset_file fixed_pkg.vhd VHDL PATH fixed_pkg.vhd
add_fileset_file float_pkg.vhd VHDL PATH float_pkg.vhd
add_fileset_file ROM_sincrona_d_tanh.vhd VHDL PATH ROM_sincrona_d_tanh.vhd
add_fileset_file ROM_sincrona_tanh.vhd VHDL PATH ROM_sincrona_tanh.vhd
add_fileset_file tanh_instruct_top.v VERILOG PATH tanh_instruct_top.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL d_tanh_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file math_utility.vhd VHDL PATH math_utility.vhd IS_CONFIGURATION_PACKAGE
add_fileset_file fixed_pkg.vhd VHDL PATH fixed_pkg.vhd
add_fileset_file float_pkg.vhd VHDL PATH float_pkg.vhd
add_fileset_file ROM_sincrona_d_tanh.vhd VHDL PATH ROM_sincrona_d_tanh.vhd
add_fileset_file ROM_sincrona_tanh.vhd VHDL PATH ROM_sincrona_tanh.vhd
add_fileset_file tanh_instruct_top.v VERILOG PATH tanh_instruct_top.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave sel_instruct n Input 1
add_interface_port nios_custom_instruction_slave num_entrada dataa Input 32
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave clk clk Input 1

