tclcmd = { ...
'vsimulink d_tanh_mem_9k -t 1ns -voptargs=+acc -f parameter_d_tanh_mem_9k.cfg -socket 51308;', ...
'add wave d_tanh_mem_9k/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\questasim64_2020.2\win64')
