setenv PATH /tools/questasim/bin:${PATH}
tclcmd = { ...
'vsimulink d_tanh_top -t 1ns -voptargs=+acc -f parameter_d_tanh_top.cfg -socket 53203;', ...
'add wave d_tanh_top/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\questasim64_2020.2\win64')
